### ISSUE TITLE
`enableTestCodeCoverage` not setting `-enableCodeCoverage` on Unity 2019

### ISSUE THREAD

**Issue by Sebu** [wooga/atlas-unity#117]
## Description

turning on CodeCoverage reporting on Unity 2019 project
```
unity {
    enableTestCodeCoverage = true
}
```
adds most code coverage parameters except `-enableCodeCoverage`.

I guess due to? shouldn't it be `<=`
https://github.com/wooga/atlas-unity/blob/master/src/main/groovy/wooga/gradle/unity/tasks/Test.groovy#L68-L70

**Comment by Joaquimmnetto** [comment]
I'll take a look on it, but it is indeed likely that the version comparison is the main cause for this.

**Comment by Joaquimmnetto** [comment]
It was indeed that, PR is open https://github.com/wooga/atlas-unity/pull/118
