### ISSUE TITLE
Add log category to UnityTask

### ISSUE THREAD

**Issue by Larusso** [wooga/atlas-unity#15]
The logs for each tasks are based on the taskname. It would be nice to add another level so you can invoke gradle multiple times with different parameters without overriding the logs and reports. This is mainly for a jenkins workflow.

The default should be `""`. There should be the 3 typical ways to set/override it.
* property in task
* property in extension
* gradle parameter `-P...=`

**Comment by Larusso** [comment]
this code line should add the log category if available:
https://github.com/wooga/atlas-unity/blob/7054f7a797113f438dd2983404e7a7bb6b5121a1/src/main/groovy/wooga/gradle/unity/tasks/AbstractUnityTask.groovy#L57

**Comment by marcolink** [comment]
WIP -> https://github.com/wooga/atlas-unity/tree/feature/add_log_category
We first have to solve an issue with our execution order to get a clean implementation.

**Comment by Larusso** [comment]
blocked by #21
